import { createFileRoute } from "@tanstack/react-router";
import { InnerPage, type Section } from "@/components/site/inner-page";
const sections: Section[] = [
 { title:{en:"About BPPA",bn:"বিপিপিএ সম্পর্কে"}, body:{en:"BPPA is developing a public platform for para pickleball in Bangladesh. Formal history, status and recognition details will be published only after official confirmation.",bn:"বিপিপিএ বাংলাদেশে প্যারা পিকলবলের জন্য একটি জনসম্মুখ প্ল্যাটফর্ম তৈরি করছে। আনুষ্ঠানিক ইতিহাস, অবস্থা ও স্বীকৃতির তথ্য নিশ্চিতকরণের পরেই প্রকাশিত হবে।"}},
 { title:{en:"Mission",bn:"মিশন"}, body:{en:"Proposed mission direction: support accessible participation, learning and responsible development of para pickleball.",bn:"প্রস্তাবিত মিশন: প্যারা পিকলবলে অ্যাক্সেসযোগ্য অংশগ্রহণ, শেখা ও দায়িত্বশীল উন্নয়নে সহায়তা করা।"}},
 { title:{en:"Vision",bn:"ভিশন"}, body:{en:"Proposed vision direction: an inclusive sporting environment where people with disabilities can discover, develop and enjoy pickleball.",bn:"প্রস্তাবিত ভিশন: এমন একটি অন্তর্ভুক্তিমূলক ক্রীড়া পরিবেশ যেখানে প্রতিবন্ধী ব্যক্তিরা পিকলবল আবিষ্কার, বিকাশ ও উপভোগ করতে পারেন।"}},
 { title:{en:"Objectives",bn:"উদ্দেশ্য"}, body:{en:"Objectives remain subject to organizational approval.",bn:"উদ্দেশ্যসমূহ সাংগঠনিক অনুমোদনের অপেক্ষায়।"}, list:[{en:"Create accessible participation pathways",bn:"অ্যাক্সেসযোগ্য অংশগ্রহণের পথ তৈরি"},{en:"Encourage safe, informed coaching",bn:"নিরাপদ ও তথ্যভিত্তিক কোচিং উৎসাহিত করা"},{en:"Build public understanding of para sport",bn:"প্যারা স্পোর্ট সম্পর্কে জনসচেতনতা তৈরি"}]},
 { title:{en:"Inclusion",bn:"অন্তর্ভুক্তি"}, body:{en:"The website uses respectful, person-centered language and presents access as a core sporting requirement—not an afterthought.",bn:"ওয়েবসাইটটি সম্মানজনক, ব্যক্তিকেন্দ্রিক ভাষা ব্যবহার করে এবং অ্যাক্সেসকে ক্রীড়ার মূল প্রয়োজন হিসেবে উপস্থাপন করে।"}},
 { title:{en:"Governance",bn:"সুশাসন"}, body:{en:"Leadership, committee structure, policies and official records will be published after verification. No governance structure is implied by this prototype.",bn:"নেতৃত্ব, কমিটি কাঠামো, নীতি ও আনুষ্ঠানিক রেকর্ড যাচাইয়ের পরে প্রকাশিত হবে। এই প্রোটোটাইপ কোনো শাসন কাঠামোর দাবি করে না।"}},
 { title:{en:"Organizational development",bn:"সাংগঠনিক উন্নয়ন"}, body:{en:"The platform is structured to grow with verified policies, programmes, reports and future digital services.",bn:"প্ল্যাটফর্মটি যাচাইকৃত নীতি, কর্মসূচি, প্রতিবেদন ও ভবিষ্যৎ ডিজিটাল সেবার সঙ্গে বিকাশের জন্য তৈরি।"}}
];
export const Route = createFileRoute("/about")({ head:()=>({meta:[{title:"About BPPA — Bangladesh Para Pickleball Association"},{name:"description",content:"Learn about BPPA's proposed mission, vision, inclusion principles and organizational development."},{property:"og:title",content:"About BPPA"},{property:"og:description",content:"BPPA's association profile, mission and inclusive development direction."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/about"}]}), component:()=> <InnerPage eyebrow={{en:"Association profile",bn:"অ্যাসোসিয়েশন প্রোফাইল"}} title={{en:"About BPPA",bn:"বিপিপিএ সম্পর্কে"}} description={{en:"A credible, accessible association platform being prepared for athletes, communities and sporting stakeholders.",bn:"অ্যাথলেট, কমিউনিটি ও ক্রীড়া অংশীজনদের জন্য প্রস্তুত একটি বিশ্বাসযোগ্য ও অ্যাক্সেসযোগ্য অ্যাসোসিয়েশন প্ল্যাটফর্ম।"}} sections={sections}/> });
