import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Play, ShieldCheck, UsersRound } from "lucide-react";
import hero from "@/assets/para-pickleball-hero.jpg";
import training from "@/assets/para-training.jpg";
import detail from "@/assets/pickleball-detail.jpg";
import { Button } from "@/components/ui/button";
import { ContentGrid, Eyebrow, Notice, SectionHeading, TextLink } from "@/components/site/content";
import { events, news, programs } from "@/content/site";
import { useSite } from "@/context/site-context";
function Index(){const{language}=useSite();const l=(en:string,bn:string)=>language==="en"?en:bn;return <>
<section className="relative min-h-[min(78vh,760px)] overflow-hidden bg-primary text-primary-foreground"><img src={hero} alt={l("Wheelchair athlete returning a pickleball on an outdoor court","আউটডোর কোর্টে হুইলচেয়ার ব্যবহারকারী অ্যাথলেট পিকলবল ফিরিয়ে দিচ্ছেন")} className="absolute inset-0 size-full object-cover object-[68%_center]" width="1600" height="1008" fetchPriority="high"/><div className="absolute inset-0 bg-hero-overlay"/><div className="relative mx-auto flex min-h-[min(78vh,760px)] max-w-7xl items-end px-5 pb-14 pt-28 md:px-8 md:pb-20"><div className="max-w-3xl"><Eyebrow>{l("Bangladesh Para Pickleball Association","বাংলাদেশ প্যারা পিকলবল অ্যাসোসিয়েশন")}</Eyebrow><h1 className="font-display text-4xl font-bold leading-[1.02] sm:text-5xl md:text-7xl">{l("Sport without barriers.","বাধাহীন ক্রীড়া।")}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/85 md:text-xl">{l("BPPA is building an accessible platform for people to discover, participate in and develop through para pickleball in Bangladesh.","বিপিপিএ বাংলাদেশে প্যারা পিকলবল আবিষ্কার, অংশগ্রহণ ও বিকাশের জন্য একটি অ্যাক্সেসযোগ্য প্ল্যাটফর্ম গড়ে তুলছে।")}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="min-h-12 bg-accent text-accent-foreground hover:bg-accent/90"><Link to="/para-pickleball">{l("Discover Para Pickleball","প্যারা পিকলবল জানুন")}<ArrowRight/></Link></Button><Button asChild variant="outline" size="lg" className="min-h-12 border-primary-foreground/50 bg-primary/40 text-primary-foreground hover:bg-primary-foreground hover:text-primary"><Link to="/about">{l("Explore BPPA","বিপিপিএ দেখুন")}</Link></Button></div></div></div></section>
<section className="border-b border-border bg-background"><div className="mx-auto grid max-w-7xl gap-0 md:grid-cols-3">{[[UsersRound,l("Inclusive participation","অন্তর্ভুক্তিমূলক অংশগ্রহণ"),l("Designed around access and sporting dignity.","অ্যাক্সেস ও ক্রীড়া মর্যাদাকে কেন্দ্র করে।")],[Play,l("Growing the sport","ক্রীড়ার বিকাশ"),l("Creating pathways for learning and play.","শেখা ও খেলার জন্য পথ তৈরি।")],[ShieldCheck,l("Responsible information","দায়িত্বশীল তথ্য"),l("Official facts published only after confirmation.","নিশ্চিতকরণের পরেই আনুষ্ঠানিক তথ্য প্রকাশ।")]].map(([Icon,title,body],i)=>{const I=Icon as typeof UsersRound;return <div key={String(title)} className="flex gap-4 border-border p-6 md:border-r md:p-8 last:border-r-0"><I className="size-6 shrink-0 text-accent-strong" aria-hidden="true"/><div><h2 className="font-bold">{String(title)}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{String(body)}</p></div></div>})}</div></section>
<section className="py-16 md:py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 md:grid-cols-2 md:px-8"><div><SectionHeading eyebrow={{en:"Purpose and direction",bn:"উদ্দেশ্য ও দিকনির্দেশনা"}} title={{en:"A credible home for an inclusive sport",bn:"অন্তর্ভুক্তিমূলক ক্রীড়ার বিশ্বাসযোগ্য ঠিকানা"}} intro={{en:"BPPA's prototype platform introduces the association's intended direction without presenting unverified history, recognition or affiliations.",bn:"বিপিপিএর প্রোটোটাইপ প্ল্যাটফর্মটি অযাচাইকৃত ইতিহাস, স্বীকৃতি বা সংযুক্তি উপস্থাপন না করে অ্যাসোসিয়েশনের কাঙ্ক্ষিত দিকনির্দেশনা তুলে ধরে।"}}/><div className="mt-8 grid gap-6 sm:grid-cols-2"><div className="border-t-2 border-accent-strong pt-4"><h3 className="font-display text-xl font-bold">{l("Mission direction","মিশনের দিক")}</h3><p className="mt-2 leading-7 text-muted-foreground">{l("Support accessible participation, learning and responsible sporting development.","অ্যাক্সেসযোগ্য অংশগ্রহণ, শেখা ও দায়িত্বশীল ক্রীড়া উন্নয়নে সহায়তা।")}</p></div><div className="border-t-2 border-primary pt-4"><h3 className="font-display text-xl font-bold">{l("Vision direction","ভিশনের দিক")}</h3><p className="mt-2 leading-7 text-muted-foreground">{l("An inclusive environment where athletes can discover and enjoy pickleball.","একটি অন্তর্ভুক্তিমূলক পরিবেশ যেখানে অ্যাথলেটরা পিকলবল আবিষ্কার ও উপভোগ করতে পারেন।")}</p></div></div><div className="mt-6"><TextLink to="/about">{l("Read the association profile","অ্যাসোসিয়েশন প্রোফাইল পড়ুন")}</TextLink></div></div><img src={training} alt={l("Inclusive group receiving pickleball coaching on court","কোর্টে অন্তর্ভুক্তিমূলক দল পিকলবল কোচিং নিচ্ছে")} className="aspect-[4/3] size-full object-cover" width="1200" height="912" loading="lazy"/></div></section>
<section className="bg-muted py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionHeading eyebrow={{en:"Prototype initiatives",bn:"প্রোটোটাইপ উদ্যোগ"}} title={{en:"Development begins with access",bn:"উন্নয়ন শুরু হয় অ্যাক্সেস দিয়ে"}} intro={{en:"These programme concepts demonstrate the future information structure. They are not confirmed BPPA programmes.",bn:"এই কর্মসূচির ধারণাগুলো ভবিষ্যৎ তথ্য কাঠামো দেখায়। এগুলো নিশ্চিত বিপিপিএ কর্মসূচি নয়।"}}/><div className="mt-10"><ContentGrid items={programs}/></div></div></section>
<section className="py-16 md:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-[0.9fr_1.1fr] md:px-8"><img src={detail} alt={l("Pickleball paddle and ball beside a sports wheelchair wheel","স্পোর্টস হুইলচেয়ারের চাকার পাশে পিকলবল প্যাডেল ও বল")} className="aspect-[4/3] size-full object-cover" width="1200" height="912" loading="lazy"/><div><SectionHeading eyebrow={{en:"Understanding the game",bn:"খেলাটি বোঝা"}} title={{en:"Adaptable by design",bn:"অভিযোজনযোগ্য নকশা"}} intro={{en:"Para pickleball can offer recreational, social and structured sporting participation. A suitable court, thoughtful equipment and respectful discussion of access needs help create a safer experience.",bn:"প্যারা পিকলবল বিনোদনমূলক, সামাজিক ও কাঠামোবদ্ধ ক্রীড়া অংশগ্রহণের সুযোগ দিতে পারে। উপযুক্ত কোর্ট, বিবেচনাপূর্ণ সরঞ্জাম ও অ্যাক্সেসের প্রয়োজন নিয়ে সম্মানজনক আলোচনা নিরাপদ অভিজ্ঞতায় সহায়তা করে।"}}/><div className="mt-6"><TextLink to="/para-pickleball">{l("Learn how participation works","অংশগ্রহণ কীভাবে কাজ করে জানুন")}</TextLink></div></div></div></section>
<section className="bg-primary py-16 text-primary-foreground md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><Eyebrow>{l("Future calendar","ভবিষ্যৎ ক্যালেন্ডার")}</Eyebrow><h2 className="font-display text-3xl font-bold md:text-5xl">{l("Sample events","নমুনা ইভেন্ট")}</h2></div><Link to="/events" className="inline-flex min-h-11 items-center gap-2 font-bold text-accent hover:underline">{l("View event structure","ইভেন্ট কাঠামো দেখুন")}<ArrowRight/></Link></div><div className="mt-10 [&_article]:bg-primary [&_article]:text-primary-foreground [&_article_p]:text-primary-foreground/70"><ContentGrid items={events} kind="event"/></div></div></section>
<section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-5 md:px-8"><Notice/><div className="mt-12"><SectionHeading eyebrow={{en:"Latest",bn:"সর্বশেষ"}} title={{en:"News & media structure",bn:"সংবাদ ও মিডিয়া কাঠামো"}}/><div className="mt-8"><ContentGrid items={news}/></div></div></div></section>
<section className="border-t border-border bg-accent py-14"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 md:flex-row md:items-center md:justify-between md:px-8"><div><h2 className="font-display text-3xl font-bold text-accent-foreground">{l("Help shape an accessible sporting future.","অ্যাক্সেসযোগ্য ক্রীড়া ভবিষ্যৎ গড়তে সহায়তা করুন।")}</h2><p className="mt-2 max-w-2xl text-accent-foreground/75">{l("Official participation and partnership channels will be published after confirmation.","আনুষ্ঠানিক অংশগ্রহণ ও অংশীদারিত্বের মাধ্যম নিশ্চিতকরণের পরে প্রকাশিত হবে।")}</p></div><Button asChild size="lg" className="min-h-12 shrink-0"><Link to="/contact">{l("Contact BPPA","বিপিপিএর সঙ্গে যোগাযোগ")}</Link></Button></div></section>
</>}
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Bangladesh Para Pickleball Association — BPPA"},{name:"description",content:"The official prototype website of the Bangladesh Para Pickleball Association, promoting accessible and inclusive participation."},{property:"og:title",content:"Bangladesh Para Pickleball Association"},{property:"og:description",content:"Building an accessible platform for para pickleball participation in Bangladesh."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}]}),component:Index});
