import { createFileRoute } from "@tanstack/react-router";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { InnerPage, type Section } from "@/components/site/inner-page";
import { useSite } from "@/context/site-context";
const sections: Section[] = [
 {title:{en:"What is para pickleball?",bn:"প্যারা পিকলবল কী?"},body:{en:"Para pickleball is an adaptable form of pickleball that can support participation by athletes with disabilities. Playing approaches and environments may be adjusted around access needs.",bn:"প্যারা পিকলবল পিকলবলের একটি অভিযোজিত রূপ যা প্রতিবন্ধী অ্যাথলেটদের অংশগ্রহণে সহায়তা করতে পারে। অ্যাক্সেসের প্রয়োজন অনুযায়ী খেলার পদ্ধতি ও পরিবেশ সামঞ্জস্য করা যায়।"}},
 {title:{en:"Inclusive participation",bn:"অন্তর্ভুক্তিমূলক অংশগ্রহণ"},body:{en:"People may participate recreationally, socially or through structured sport pathways. Individual needs should be discussed respectfully before play.",bn:"মানুষ বিনোদনমূলক, সামাজিক বা কাঠামোবদ্ধ ক্রীড়া পথে অংশ নিতে পারেন। খেলার আগে ব্যক্তিগত প্রয়োজন সম্মানের সঙ্গে আলোচনা করা উচিত।"}},
 {title:{en:"Playing environment",bn:"খেলার পরিবেশ"},body:{en:"A clear, level court, safe circulation space and accessible entry points support a better experience. Venue suitability should be reviewed for each activity.",bn:"পরিষ্কার, সমতল কোর্ট, নিরাপদ চলাচলের স্থান ও অ্যাক্সেসযোগ্য প্রবেশপথ ভালো অভিজ্ঞতায় সহায়তা করে। প্রতিটি কার্যক্রমের জন্য ভেন্যুর উপযোগিতা পর্যালোচনা করা উচিত।"}},
 {title:{en:"Equipment overview",bn:"সরঞ্জামের সংক্ষিপ্ত বিবরণ"},body:{en:"Typical equipment includes paddles, perforated balls, a net and court markings. Adaptive equipment may be used according to an athlete's needs.",bn:"সাধারণ সরঞ্জামের মধ্যে প্যাডেল, ছিদ্রযুক্ত বল, নেট ও কোর্টের দাগ রয়েছে। অ্যাথলেটের প্রয়োজন অনুযায়ী অভিযোজিত সরঞ্জাম ব্যবহার করা যেতে পারে।"}},
 {title:{en:"Accessibility considerations",bn:"অ্যাক্সেসিবিলিটি বিবেচনা"},body:{en:"Consider routes to court, surface quality, rest space, communication needs, accessible toilets and suitable emergency planning.",bn:"কোর্টে যাওয়ার পথ, পৃষ্ঠের মান, বিশ্রামের স্থান, যোগাযোগের প্রয়োজন, অ্যাক্সেসযোগ্য টয়লেট ও উপযুক্ত জরুরি পরিকল্পনা বিবেচনা করুন।"}},
 {title:{en:"Participation pathways",bn:"অংশগ্রহণের পথ"},body:{en:"Future pathways may include introductory sessions, regular training, coaching support and appropriate competition opportunities. Details are pending confirmation.",bn:"ভবিষ্যৎ পথে পরিচিতি সেশন, নিয়মিত প্রশিক্ষণ, কোচিং সহায়তা ও উপযুক্ত প্রতিযোগিতার সুযোগ থাকতে পারে। বিস্তারিত নিশ্চিতকরণের অপেক্ষায়।"}},
 {title:{en:"Safety considerations",bn:"নিরাপত্তা বিবেচনা"},body:{en:"Participants should use suitable equipment, warm up, communicate access needs and follow qualified medical or coaching advice where relevant.",bn:"অংশগ্রহণকারীদের উপযুক্ত সরঞ্জাম ব্যবহার, ওয়ার্ম-আপ, অ্যাক্সেসের প্রয়োজন জানানো এবং প্রাসঙ্গিক ক্ষেত্রে যোগ্য চিকিৎসা বা কোচিং পরামর্শ অনুসরণ করা উচিত।"}}
];
function Page(){const{language}=useSite();return <><InnerPage eyebrow={{en:"Learn the sport",bn:"খেলা সম্পর্কে জানুন"}} title={{en:"Para Pickleball",bn:"প্যারা পিকলবল"}} description={{en:"An accessible introduction to the sport, its environment and thoughtful participation—without presenting unconfirmed classification rules.",bn:"অনিশ্চিত শ্রেণিবিন্যাস বিধি উপস্থাপন না করে খেলা, পরিবেশ ও বিবেচনাপূর্ণ অংশগ্রহণের একটি সহজ পরিচিতি।"}} sections={sections}/><section className="bg-muted"><div className="mx-auto max-w-4xl px-5 py-16 md:px-8"><h2 className="font-display text-3xl font-bold">{language==="en"?"Frequently asked questions":"সাধারণ প্রশ্ন"}</h2><Accordion type="single" collapsible className="mt-6"><AccordionItem value="one"><AccordionTrigger>{language==="en"?"Who may participate?":"কারা অংশ নিতে পারেন?"}</AccordionTrigger><AccordionContent>{language==="en"?"Participation depends on the activity, venue and individual access needs. Official BPPA participation guidance will be published after confirmation.":"অংশগ্রহণ কার্যক্রম, ভেন্যু ও ব্যক্তিগত অ্যাক্সেসের প্রয়োজনের ওপর নির্ভর করে। আনুষ্ঠানিক নির্দেশনা নিশ্চিতকরণের পরে প্রকাশিত হবে।"}</AccordionContent></AccordionItem><AccordionItem value="two"><AccordionTrigger>{language==="en"?"Are classification rules available here?":"শ্রেণিবিন্যাসের নিয়ম কি এখানে আছে?"}</AccordionTrigger><AccordionContent>{language==="en"?"No. This prototype does not publish or imply official eligibility or classification rules.":"না। এই প্রোটোটাইপ আনুষ্ঠানিক যোগ্যতা বা শ্রেণিবিন্যাসের নিয়ম প্রকাশ বা দাবি করে না।"}</AccordionContent></AccordionItem></Accordion></div></section></>}
export const Route=createFileRoute("/para-pickleball")({head:()=>({meta:[{title:"What Is Para Pickleball? — BPPA"},{name:"description",content:"An accessible introduction to para pickleball participation, equipment, environments and safety."},{property:"og:title",content:"Discover Para Pickleball — BPPA"},{property:"og:description",content:"Understand inclusive pickleball participation and accessible playing environments."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/para-pickleball"}]}),component:Page});
