import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, MapPin } from "lucide-react";
import type { ContentCard, Localized, RoutePath } from "@/content/site";
import { t } from "@/content/site";
import { useSite } from "@/context/site-context";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="mb-3 text-xs font-bold uppercase tracking-[0.16em] text-accent-strong">{children}</p>; }
export function SectionHeading({ eyebrow, title, intro, align = "left" }: { eyebrow?: Localized; title: Localized; intro?: Localized; align?: "left" | "center" }) {
  const { language } = useSite();
  return <div className={align === "center" ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}>{eyebrow && <Eyebrow>{t(eyebrow, language)}</Eyebrow>}<h2 className="font-display text-3xl font-bold leading-tight text-foreground md:text-5xl">{t(title, language)}</h2>{intro && <p className="mt-5 text-base leading-7 text-muted-foreground md:text-lg">{t(intro, language)}</p>}</div>;
}
export function TextLink({ to, children }: { to: RoutePath; children: React.ReactNode }) { return <Link to={to} className="inline-flex min-h-11 items-center gap-2 font-bold text-primary underline-offset-4 hover:underline">{children}<ArrowRight aria-hidden="true" /></Link>; }
export function Notice() { const { language } = useSite(); return <div className="border-l-4 border-accent-strong bg-muted px-5 py-4 text-sm font-semibold text-foreground" role="note">{language === "en" ? "Prototype notice: information shown here is sample content pending official confirmation." : "প্রোটোটাইপ বিজ্ঞপ্তি: এখানে প্রদর্শিত তথ্য আনুষ্ঠানিক নিশ্চিতকরণের অপেক্ষায় থাকা নমুনা বিষয়বস্তু।"}</div>; }
export function ContentGrid({ items, kind = "standard" }: { items: ContentCard[]; kind?: "standard" | "event" }) { const { language } = useSite(); return <div className="grid gap-px bg-border md:grid-cols-3">{items.map((item) => <article key={item.id} className="min-w-0 bg-background p-6 md:p-8"><span className="text-[0.7rem] font-bold uppercase tracking-[0.14em] text-accent-strong">{item.tag ? t(item.tag, language) : t({ en: "PROGRAM CONCEPT", bn: "কর্মসূচির ধারণা" }, language)}</span><h3 className="mt-5 font-display text-xl font-bold leading-snug text-foreground">{t(item.title, language)}</h3><p className="mt-3 leading-7 text-muted-foreground">{t(item.summary, language)}</p>{item.meta && <p className="mt-5 flex items-start gap-2 text-sm font-semibold text-foreground">{kind === "event" ? <CalendarDays className="mt-0.5 size-4 shrink-0" aria-hidden="true" /> : <MapPin className="mt-0.5 size-4 shrink-0" aria-hidden="true" />}{t(item.meta, language)}</p>}</article>)}</div>; }
export function PageIntro({ eyebrow, title, description }: { eyebrow: Localized; title: Localized; description: Localized }) { const { language } = useSite(); return <header className="bg-primary text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-14 md:px-8 md:py-20"><Eyebrow>{t(eyebrow, language)}</Eyebrow><h1 className="max-w-4xl font-display text-4xl font-bold leading-[1.06] md:text-6xl">{t(title, language)}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-primary-foreground/80">{t(description, language)}</p></div></header>; }
export function EmptyState({ title, body }: { title: Localized; body: Localized }) { const { language } = useSite(); return <div className="border border-dashed border-border bg-muted p-8 text-center"><h3 className="font-display text-xl font-bold">{t(title, language)}</h3><p className="mt-2 text-muted-foreground">{t(body, language)}</p></div>; }
