import { useEffect, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Menu, X } from "lucide-react";
import logo from "@/assets/bppa-logo.png.asset.json";
import { Button } from "@/components/ui/button";
import { navItems, t } from "@/content/site";
import { useSite } from "@/context/site-context";
import { AccessibilityMenu } from "./accessibility-menu";

export function LanguageSwitcher({ compact = false }: { compact?: boolean }) { const { language, setLanguage } = useSite(); return <div className="inline-flex min-h-11 items-center border border-border bg-background p-1" role="group" aria-label={language === "en" ? "Select language" : "ভাষা নির্বাচন করুন"}><Button variant={language === "en" ? "default" : "ghost"} size="sm" className="min-h-9 px-3" lang="en" onClick={() => setLanguage("en")} aria-pressed={language === "en"}>EN{!compact && <span className="sr-only"> English</span>}</Button><Button variant={language === "bn" ? "default" : "ghost"} size="sm" className="min-h-9 px-3" lang="bn" onClick={() => setLanguage("bn")} aria-pressed={language === "bn"}>বাংলা</Button></div>; }

export function SiteHeader() {
  const { language } = useSite(); const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null); const menu = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; menu.current?.querySelector<HTMLAnchorElement>("a")?.focus(); const close = (e: KeyboardEvent) => { if (e.key === "Escape") { setOpen(false); trigger.current?.focus(); } }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open]);
  return <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-sm"><div className="mx-auto grid min-h-20 max-w-7xl grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-4 md:px-8"><Link to="/" className="flex min-w-0 items-center gap-3" aria-label={language === "en" ? "BPPA home" : "বিপিপিএ হোম"}><img src={logo.url} alt="" className="size-14 shrink-0 object-contain" width="64" height="64"/><span className="min-w-0"><strong className="block truncate font-display text-lg leading-tight text-primary">BPPA</strong><span className="hidden truncate text-xs font-semibold text-muted-foreground sm:block">{language === "en" ? "Bangladesh Para Pickleball Association" : "বাংলাদেশ প্যারা পিকলবল অ্যাসোসিয়েশন"}</span></span></Link><div className="flex items-center gap-2"><nav className="hidden lg:block" aria-label={language === "en" ? "Main navigation" : "প্রধান নেভিগেশন"}><ul className="flex items-center">{navItems.map((item) => <li key={item.path}><Link to={item.path} activeOptions={{ exact: item.path === "/" }} className="flex min-h-11 items-center border-b-2 border-transparent px-3 text-sm font-bold text-foreground hover:text-primary" activeProps={{ className: "border-accent-strong text-primary" }}>{t(item.label, language)}</Link></li>)}</ul></nav><div className="hidden sm:block"><LanguageSwitcher compact /></div><AccessibilityMenu/><Button ref={trigger} variant="outline" size="icon" className="min-h-11 min-w-11 lg:hidden" aria-label={open ? (language === "en" ? "Close menu" : "মেনু বন্ধ করুন") : (language === "en" ? "Open menu" : "মেনু খুলুন")} aria-expanded={open} aria-controls="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</Button></div></div>{open && <div ref={menu} id="mobile-menu" className="border-t border-border bg-background px-4 pb-5 lg:hidden"><nav aria-label={language === "en" ? "Mobile navigation" : "মোবাইল নেভিগেশন"}><ul>{navItems.map((item) => <li key={item.path}><Link to={item.path} className="flex min-h-12 items-center border-b border-border font-bold" activeProps={{ className: "text-primary" }} onClick={() => setOpen(false)}>{t(item.label, language)}</Link></li>)}</ul></nav><div className="mt-4 sm:hidden"><LanguageSwitcher/></div></div>}</header>;
}
